services:
  api:
    build: 
      context: .
      dockerfile: app/Docker/python/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/spatial_db
    volumes:
      - .:/app
    restart: always


  db:
    image: postgis/postgis:17-master
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spatial_db
    ports:
      - "5432:5432"
    volumes:
      - ./app/Docker/postgis/init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: