services:
  api:
    build: 
      context: .
      dockerfile: app/Docker/python/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=spatial_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    volumes:
      - .:/app
    restart: always


  db:
    image: postgis/postgis:17-master
    hostname: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spatial_db
    ports:
      - "5432:5432"
    volumes:
      - ./app/Docker/postgis/init:/docker-entrypoint-initdb.d
      - ./app/Docker/postgis/data:/var/lib/postgresql/data
    restart: always
